### Configuration for Site
title: Jiahao Zhang

### Configuration for home
home_title: Jiahao's Homepage
avatar: assets/home/avatar.jpg
description: assets/home/description.md
cv: assets/home/CV.pdf

name: Jiahao Zhang(张佳豪)
email: zhangjiahao2022@stu.pku.edu.cn
github: https://github.com/jhzhics
phone: +86 15736751047